
spring:
#  redis:
#    database: 0
#    host: localhost
#    port: 6379
#    password: 123456

  redis:
    database: 0
    host: 192.168.1.153
    port: 6379

#   连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 8
        min-idle: 8

#       连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        max-idle: 8

#     连接超时时间（毫秒）
      timeout: 0

# 在 192.168.1.153:9200 的响应体中有这些信息,es的http端口是9200，但是java节点端口是9300
  data:
    elasticsearch:
#     名称必须与 9200 访问到的名称相同
      cluster-name: elasticsearch
      cluster-nodes: 192.168.1.153:9300
#      使用默认的仓库
      repositories:
        enabled: true

  elasticsearch:
    jest:
      uris: http://192.168.1.153:9200


