
spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: localhost
    port: 6379
    password: 123456
    # 连接超时时间（毫秒）
    timeout: 10000

    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        max-idle: 8
        min-idle: 0
      # 关闭超时时间（毫秒）
      shutdown-timeout: 100

  #添加Thymeleaf配置
  thymeleaf:
    enabled: true
    mode: HTML
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html

    resources:
      static-locations: classpath:/static/



  # 在 192.168.1.153:9200 的响应体中有这些信息,es的http端口是9200，但是java节点端口是9300
  data:
    elasticsearch:
      #     名称必须与 9200 访问到的名称相同
      cluster-name: elasticsearch
      cluster-nodes: 192.168.1.153:9300
      #      使用默认的仓库
      repositories:
        enabled: true

  elasticsearch:
    jest:
      uris: http://192.168.1.153:9200

  # 注意此邮箱密码不是真正的密码，而是邮箱设置中 POP3/SMTP等服务第三方登录的授权码
  mail:
    username: huaimin3@sina.com
    password: abcdwdv
    host: smtp.sina.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true

# 配置根节点日志，hibernate 日志级别为 INFO
logging:
  level:
    root: info
    org.hibernate: info
    #   打印 sql 语句时，同时打印 sql 参数及值，与 show-sql 有一定的联系
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace


